[workspace]
members = [
    "brotli",
    "crypto-hashes",
    "cssparser",
    "flac",
    "httparse",
    "lz4-compress",
    "mp4parse",
    "pulldown-cmark",
    "quick-xml",
    "regex",
    "rustfmt",
    "serde_json",
    "tar",
    "xml-rs",
]
